### ISSUE TITLE
ClassNotFoundException:com.google.android.gms.analytics.GoogleAnalytics Unity 5.3.1f

### ISSUE THREAD

**Issue by Disar** [googleanalytics/google-analytics-plugin-for-unity#100]
Using Unity 5.3.1 and Google SDK 8.4 I get the following error. The game compiles fine but crashes on runtime. Im also using [this plugin](https://github.com/playgameservices/play-games-plugin-for-unity) which forces the AAR files of version 8.4.
      

      AndroidJavaException:java.lang.ClassNotFoundException:com.google.android.gms.analytics.GoogleAnalytics
       java.lang.ClassNotFoundException: com.google.android.gms.analytics.GoogleAnalytics
      at java.lang.Class.classForName(Native Method)
      at java.lang.Class.forName(Class.java:309)
      at java.lang.Class.forName(Class.java:273)
      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
      at com.unity3d.player.UnityPlayer.a(Unknown Source)
      at com.unity3d.player.UnityPlayer$b.run(Unknown Source)

Any advice?

Edit:

When I used the Play games plugin I also had to add a dependency :

       svcSupport.DependOn("com.google.android.gms","play-services-ads",PluginVersion.PlayServicesVersionConstraint);

Perhaps I need manually add a dependency that works for analytics?

**Comment by Disar** [comment]
Welp adding 
      svcSupport.DependOn("com.google.android.gms","play-services-analytics",PluginVersion.PlayServicesVersionConstraint);

Sorry for the false alarm
