### ISSUE TITLE
Google Analytics Android Tracker not initialising correctly

### ISSUE THREAD

**Issue by ManuelEMR** [googleanalytics/google-analytics-plugin-for-unity#118]
Im currently using GAv4 and after copying play-services-analytics-8.4.0.aar from {android-sdk}\extras\google\m2repository\com\google\android\gms\play-services-analytics\8.4.0 to Assets/Plugins/Android folder i get a new NoClassDefFoundError

AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzx;
                                        java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzx;
                                            at com.google.android.gms.analytics.internal.zzf.zzaa(Unknown Source)
                                            at com.google.android.gms.analytics.GoogleAnalytics.getInstance(Unknown Source)
                                            at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                            at com.unity3d.player.UnityPlayer.a(Unknown Source)
                                            at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzx" on path: DexPathList[[zip file "/data/app/com.icogroup.flips-1/base.apk"],nativeLibraryDirectories=[/data/app/com.icogroup.flips-1/lib/arm, /vendor/lib, /system/lib]]
                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                            at com.google.android.gms.analytics.internal.zzf.zzaa(Unknown Source) 
                                            at com.google.android.gms.analytics.GoogleAnalytics.getInstance(Unknown Source) 
                                            at com.unity3d.player.UnityPlayer.nativeRender(Native Method) 
                                            at com.unity3d.player.UnityPlayer.a(Unknown Source) 
                                            at com.unity3d.player.UnityPlayer$b.run(Unknown Source) 
04-04 13:43:10.812 6317-6389/? D/Unity: Unloading 5 Unused Serialized files (Serialized files now loaded: 0)

And Android Tracker never initializes, so i cant send events. Has anyone had this problem?

**Comment by trellos** [comment]
Is there any progress on this? I'm getting the same issue. Latest (as of today) google analytics, Unity 5.3.4f1.

**Comment by c9iner** [comment]
I'm also getting this issue with latest google analytics 8.3.0 and 8.4.0 and Unity 5.3.1f1

**Comment by ZahraHeydari** [comment]
I received this error but after setting google analytics version 8.4.0 to 9.0.0,all errors were gone!

**Comment by muratmenevse** [comment]
Any news? I still have this problem :/ Version upgrade 9.0.0 did not work for me.

**Comment by RandomCouch** [comment]
I'm also having this issue, I've tried with 8.4.0, 9.0.0, 10.0.0 and 11.0.4 ... I seem to keep getting this error 
AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzx;
