### ISSUE TITLE
GA4 Unity problem AndroidJavaException?

### ISSUE THREAD

**Issue by kkohno** [googleanalytics/google-analytics-plugin-for-unity#177]
I getting the following issue on android. Dug in plugin - I made an empty project to check this.  On Editor is ok.

adb logcat:

AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/Preconditions;
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/Preconditions;
 	at com.google.android.gms.internal.measurement.zzat.zzc(Unknown Source)
 	at com.google.android.gms.analytics.GoogleAnalytics.getInstance(Unknown Source)
 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
 	at com.unity3d.player.UnityPlayer.c(Unknown Source)
 	at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
 	at android.os.MessageQueue.next(MessageQueue.java:392)
 	at android.os.Looper.loop(Looper.java:136)
 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.Preconditions" on path: DexPathList[[zip file "/data/app/com.pixel.gun.combats-1/base.apk"],nativeLibraryDirectories=[/data/app/com.pixel.gun.combats-1/lib/arm, /data/app/com.pixel.gun.com

**Comment by ido567** [comment]
Did you find the problem?

**Comment by ColorTwist** [comment]
Same here- 2018.2.6

**Comment by ido567** [comment]
Eventually, I didn't use the SDK directly and used this plugin: https://assetstore.unity.com/packages/3d/characters/google-analytics-sdk-16317
