### ISSUE TITLE
Unable to instantiate receiver com.google.analytics.tracking.android.CampaignTrackingReceiver: java.lang.ClassNotF

### ISSUE THREAD

**Issue by mohan1234** [googleanalytics/google-analytics-plugin-for-unity#87]
When I open the app after first screen my app got crash. Following is the crash Log:- 

java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 5.2.1p1
Device model      : LENOVO Lenovo A7000-a
Device fingerprint: Lenovo/aio_row/A7000-a:5.0/LRX21M/RA7000-a_S152_150917_ROW.09171000:user/release-keys
Caused by: java.lang.RuntimeException: Unable to instantiate receiver com.google.analytics.tracking.android.CampaignTrackingReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.analytics.tracking.android.CampaignTrackingReceiver" on path: DexPathList[[zip file "/data/app/com.games2win.gullycricket-1/base.apk"],nativeLibraryDirectories=[/data/app/com.games2win.gullycricket-1/lib/arm, /vendor/lib, /system/lib]]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2755)
	at android.app.ActivityThread.access$1700(ActivityThread.java:176)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5576)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.analytics.tracking.android.CampaignTrackingReceiver" on path: DexPathList[[zip file "/data/app/com.games2win.gullycricket-1/base.apk"],nativeLibraryDirectories=[/data/app/com.games2win.gullycricket-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2750)
	... 9 more
	Suppressed: java.lang.ClassNotFoundException: com.google.analytics.tracking.android.CampaignTrackingReceiver
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 11 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by alexpwer** [comment]
I'm getting the same, here is the error log:

java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 5.3.1f1
Device model      : samsung SM-G920I
Device fingerprint: samsung/zerofltedv/zeroflte:5.1.1/LMY47X/G920IDVU3DOK9:user/release-keys
Caused by: java.lang.RuntimeException: Unable to instantiate receiver com.google.analytics.tracking.android.CampaignTrackingReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.analytics.tracking.android.CampaignTrackingReceiver" on path: DexPathList[[zip file "/data/app/com.ingg.werfootball-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ingg.werfootball-1/lib/arm, /vendor/lib, /system/lib]]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3466)
	at android.app.ActivityThread.access$1900(ActivityThread.java:198)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1759)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6843)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.analytics.tracking.android.CampaignTrackingReceiver" on path: DexPathList[[zip file "/data/app/com.ingg.werfootball-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ingg.werfootball-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3461)
	... 9 more
	Suppressed: java.lang.ClassNotFoundException: com.google.analytics.tracking.android.CampaignTrackingReceiver
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 11 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by chijikpijik** [comment]
+

**Comment by swaps-mayekar** [comment]
Anybody has any solution for this situation ? I am getting the same error on Android devices.
Everything works fine on iOS and Unity Editor but not on Android :(

**Comment by chijikpijik** [comment]
@swaps-mayekar you get this error on all devices (or could you reproduce it)?

**Comment by njovy** [comment]
I'm getting this error as well.

**Comment by swaps-mayekar** [comment]
@chijikpijik @njovy  Yes, I am able to reproduce this error on all devices :(
Solution for this seems to be given [here](https://github.com/googleanalytics/google-analytics-plugin-for-unity/issues/108) but I am not able to find the **play-services-analytics-8.4.0.aar** in Android SDK directory (I am on mac).

Does anybody have idea about where to get this file ? :/

**Comment by swaps-mayekar** [comment]
This issue was fixed after installing Play services library :+1:

**Comment by Riddhesh** [comment]
@swaps-mayekar  You installed Play Services Library in Project??

I am facing the same issue. 

Here is the Log :

java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 5.3.3f1
Device model      : samsung SM-G531H
Device fingerprint: samsung/grandprimeve3gxx/grandprimeve3g:5.1.1/LMY48B/G531HXXU0AOG1:user/release-keys
Caused by: java.lang.RuntimeException: Unable to instantiate receiver com.google.analytics.tracking.android.CampaignTrackingReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.analytics.tracking.android.CampaignTrackingReceiver" on path: DexPathList[[zip file "/data/app/com.world3dgames.riversand.excavator-1/base.apk"],nativeLibraryDirectories=[/data/app/com.world3dgames.riversand.excavator-1/lib/arm, /vendor/lib, /system/lib]]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2992)
	at android.app.ActivityThread.access$1800(ActivityThread.java:177)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5910)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.analytics.tracking.android.CampaignTrackingReceiver" on path: DexPathList[[zip file "/data/app/com.world3dgames.riversand.excavator-1/base.apk"],nativeLibraryDirectories=[/data/app/com.world3dgames.riversand.excavator-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2987)
	... 9 more
	Suppressed: java.lang.ClassNotFoundException: com.google.analytics.tracking.android.CampaignTrackingReceiver
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 11 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

I am using AdMob 3.0.5 and Analytics v4. I copied 

play-services-analytics-9.4.0.aar and
play-services-analytics-impl-9.4.0.aar 

manually from Android SDK in Plugins/Andoird folder

I am not getting crash in my device while testing. But once publishing the build, every 100th player is getting crash problem that i can see in Crash Report on Google Play Developer Portal
