### ISSUE TITLE
ERROR - Service Intent must be explicit: Intent { act=com.google.android.gms.analytics.service.START (has extras) }

### ISSUE THREAD

**Issue by mauricio-jmmendes** [googleanalytics/google-analytics-plugin-for-unity#91]
1	11-04 08:53:09.658: E/AndroidRuntime(23934): FATAL EXCEPTION: GAThread
2	11-04 08:53:09.658: E/AndroidRuntime(23934): Process: com.xxx.xxx.xxx, PID: 23934
3	11-04 08:53:09.658: E/AndroidRuntime(23934): java.lang.Error: FATAL EXCEPTION [GAThread]
4	11-04 08:53:09.658: E/AndroidRuntime(23934): Unity version     : 5.0.1f1
5	11-04 08:53:09.658: E/AndroidRuntime(23934): Device model      : Sony E6653
6	11-04 08:53:09.658: E/AndroidRuntime(23934): Device fingerprint: Sony/E6653/E6653:5.1.1/32.0.A.7.86/2688030552:userdebug/release-keys
7	11-04 08:53:09.658: E/AndroidRuntime(23934): Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.google.android.gms.analytics.service.START (has extras) }
8	11-04 08:53:09.658: E/AndroidRuntime(23934):    at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1695)
9	11-04 08:53:09.658: E/AndroidRuntime(23934):    at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1794)
10	11-04 08:53:09.658: E/AndroidRuntime(23934):    at android.app.ContextImpl.bindService(ContextImpl.java:1772)
11	11-04 08:53:09.658: E/AndroidRuntime(23934):    at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
12	11-04 08:53:09.658: E/AndroidRuntime(23934):    at com.google.analytics.tracking.android.AnalyticsGmsCoreClient.connect(AnalyticsGmsCoreClient.java:82)
13	11-04 08:53:09.658: E/AndroidRuntime(23934):    at com.google.analytics.tracking.android.GAServiceProxy.connectToService(GAServiceProxy.java:279)
14	11-04 08:53:09.658: E/AndroidRuntime(23934):    at com.google.analytics.tracking.android.GAServiceProxy.createService(GAServiceProxy.java:163)
15	11-04 08:53:09.658: E/AndroidRuntime(23934):    at com.google.analytics.tracking.android.GAThread.init(GAThread.java:95)
16	11-04 08:53:09.658: E/AndroidRuntime(23934):    at com.google.analytics.tracking.android.GAThread.run(GAThread.java:493)

I got this crash when running my app to evento to GA, any suggestions on how to solve this issue?

**Comment by arunavsikdershuvo** [comment]
@mauricio-jmmendes did you solve this problem? I’m facing this now for an old project. Please share if you have some idea how to solve this.
